---

- include: install_source.yml
  when: "{{ bitcoind_install_source }}"
  tags: [bitcoind, install]

- include: install_package.yml
  when: "{{ not bitcoind_install_source }}"
  tags: [bitcoind, install]

- include: users_and_groups.yml
  tags: [bitcoind]
    
- name: Ensure data directory exists
  file: path="{{ bitcoind_data_dir }}" state=directory owner="{{ bitcoind_user }}" group="{{ bitcoind_group }}" mode=0755
  tags: [bitcoind, dirs]

- name: Ensure configuration directory exists
  file: path="{{ bitcoind_conf_dir }}" state=directory owner=root group=root mode=0755
  tags: [bitcoind, dirs]

- name: Create configuration file
  template: src="bitcoind.conf.j2" dest="{{ bitcoind_conf_dir }}/bitcoind.conf" owner=root group="{{ bitcoind_group }}" mode=0640
  notify:
    - restart bitcoind
  tags: [bitcoind, config]

- name: Create upstart configuration file
  template: src=upstart.conf.j2 dest=/etc/init/bitcoind.conf owner=root group=root mode=0644
  when: ansible_os_family == "Debian"
  notify:
    - restart bitcoind
  tags: [bitcoind, config, service]

- name: Start bitcoind
  service: name=bitcoind state="{{bitcoind_state}}" enabled="{{ bitcoind_enable }}"
  tags: [bitcoind, service]

